spring:
  cloud:
    gateway:
      routes:
      - id: openapi
        uri: http://localhost:8081
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/subscription, /v3/api-docs
      - id: subscription-service
        uri: http://localhost:8081/subscription
        predicates:
        - Path=/subscription
        filters:
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback

springdoc:
