spring:
  cloud:
    gateway:
      routes:
      - id: swagger
        uri: http://localhost:8081/swagger-ui.html
        predicates:
        - Path=/swagger-ui.html
      - id: subscription
        uri: http://localhost:8081/subscription
        predicates:
        - Path=/subscription
        filters:
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback