spring:
  cloud:
    gateway:
      routes:
      - id: subscription
        uri: http://subscription-service:8081/subscription
        predicates:
        - Path=/subscription
        filters:
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback