version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INTERNAL://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://169.132.90.228:9092,INTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 50000
      KAFKA_LOG_RETENTION_MS: 50000
      KAFKA_CREATE_TOPICS: "subscription:1:1"