email:
  from: abs.test.adidas@gmail.com
  subject: Subscription email!
  password: af5db8d3d72da576a5a758dfe4311d14

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: adidas-email-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      properties:
        spring.json.value.default.type: com.adidas.email.subscription.Subscription

gmail:
  mail:
    smtp:
      host: smtp.gmail.com
      socketFactory.port: 465
      socketFactory.class: javax.net.ssl.SSLSocketFactory
      auth: true
      port: 465